---
  - name: Configure Elk VM with Docker
    hosts: elk
    remote_user: azdmin
    become: true
    tasks:
    
    # Use apt module to install docker
    - name: Install docker.io
      apt:
        update_cache: yes
        force_apt_get: yes
        name: docker.io
        state: present

    # Use apt module to install pip
    - name: Install python3-pip
      apt:
        force_apt_get: yes
        name: python3-pip
        state: present

    # Use pip module (It will default to pip3)
    - name: Install Docker module
      pip:
        name: docker
        state: present

    # Use command module to increase virtual memory
    - name: Increase virtual memory
      command: sysctl -w vm.max_map_count=262144

    # Use sysctl module
    - name: Use more memory
      sysctl:
        name: vm.max_map_count
        value: "262144"
        state: present
        reload: yes

    # Use docker_container module to launch an elk container with docker
    # Restart the container everytime the VM restarts
    - name: download and launch a docker elk container
      docker_container:
        name: elk
        image: sebp/elk:761
        state: started
        restart_policy: always
        # The ports that ELK runs on
        published_ports:
          - 5601:5601
          - 9200:9200
          - 5044:5044

    # Start the container whenever the VM boots up
    - name: Enable service docker on boot
      systemd:
        name: docker
        enabled: yes


      
